name: Auto merge dependabot

on:
  pull_request:

jobs:
  auto-merge:
    name: Auto merge pull requests from dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto-merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.GHCR_PAT }}
